### ISSUE TITLE
running maja in backward mode

### ISSUE THREAD

**Issue by Giovanni-Sabatino** [olivierhagolle/Start_maja#13]
Dears

 I am trying to run MAJA on the following two products:

S2A_MSIL1C_20170108T095401_N0204_R079_T33UWQ_20170108T095355
S2A_MSIL1C_20170111T100351_N0204_R122_T33UWQ_20170111T100351

obtaining the following error:

2018-07-18T04:01:58.623175 wnode0029.gpod.local maja-processing 01.00 [000000007683] [E] vns::Data::ERROR: ComputeEnvironmentCorrectionImageFilter(0x2461430): The images 'l_IPTOCPtr' (size [10980, 10980]) and 'l_L2EDGPtr' (size [1098, 1098]) have not the same size !  [vnsComputeEnvironmentCorrectionImageFilter.txx:CheckInputs:128]

see here for the complete log file: 
http://gpod.eo.esa.int/proxy4.aspx?url=http://grid-eo-serv01.esrin.esa.int/gridify-logs/S_153187496758091685373661161833/MAJA/30464/majaproc_L2BACKWARD.log

Indeed I notice that the python script producing AUX data, tuilage_mnt_eau_S2.py, is producing 1098X1098 AUX data raster size, while the input tile is 10980X10980. 
What can cause this reduction of a factor 10X10?

Thank you.
Giovanni Sabatino

**Comment by Giovanni-Sabatino** [comment]
maybe this information adds something:
when I run the python code to create S2 AUX data I notice the message:

e011n44
missing SWBD watr file :  e011n44
it is a fully land tile
/data/MAJA/aux_data/SRTM_WaterBody_Data//e011n44.gml
#############Fichier eau : /data/MAJA/aux_data/SRTM_WaterBody_Data//e011n44.gml
gdal_rasterize -burn 0 -l e011n44 /data/MAJA/aux_data/SRTM_WaterBody_Data//e011n44.gml /data/MAJA/aux_data/SRTM_WaterBody_Data//srtm_39_04_tmp.tif
Warning : the output raster dataset has a SRS, but the input vector layer SRS is unknown.
Ensure input vector has the same SRS, otherwise results might be incorrect.
0...10...20...30...40...50...60...70...80...90...100 - done.

**Comment by olivierhagolle** [comment]
Hi Giovanni, 
did we solve your issues (we discussed via email), or do you still need help on that point ?
Best regards,
Olivier

**Comment by Giovanni-Sabatino** [comment]
Hi Olivier,
forcing the aux data size to be 10980X10980 fixed the issue: we need to add an extra **0**

proj=UTM29N
EPSG_out=32629
chaine_proj=EPSG:32629
tx_min=0
ty_min=0
tx_max=0
ty_max=0
pas_x=10980**0**
pas_y=10980**0**
orig_x=499980
orig_y=6100020
marge=0

**Comment by olivierhagolle** [comment]
OK thanks, so I can close the issue.
By the way, I am interested to know about your use of MAJA and the results you find (via email, not on github)
Best regards
Olivier
