### ISSUE TITLE
DTM, missing module - osgeo

### ISSUE THREAD

**Issue by fraunos** [olivierhagolle/Start_maja#17]
Hi,
I managed to install maja from binary package - now I'm trying to generate DTM from STRM data. While running `python tuilage_mnt_eau_S2.py -p parameters.txt -s 32SNE.txt -m SRTM` I get an error `No module named osgeo`. It was the same with numpy - which was easy to solve with `pipenv install numpy`. The problem is `pip` does not find any package named `osgeo`.
Any suggestions?

**Comment by olivierhagolle** [comment]
Hi,
osgeo usually comes with gdal. Installing gdal should also instal osgeo.
Hopefully ;)
Olivier

**Comment by fraunos** [comment]
Thanks,
I guess it's outside of Your scope then - installing `gdal` package neither works. Oh, Python dependency management...

**Comment by fraunos** [comment]
Okay, fixed it with proper pyenv setup - anaconda2
