### ISSUE TITLE
Problems running MAJA

### ISSUE THREAD

**Issue by RiccardoOr** [olivierhagolle/Start_maja#23]
Dear all,
I'm new to using Maja and I have a problem.
First of all, I state that I am using "normal" Maja, not start_maja.py, and I should extract the shadow mask from an image.
If I have understood correctly to do so I have to use a time series, then using the NOMINAL mode.
after some failed attempts I succeeded in this:
- analyzed the image at time t0 with INIT mode;
- putting the L2VALD output folder in the input folder;
- analyzed the image at time t0 + 1 in NOMINAL mode.
During processing, the L2VALD folder is read, but remains pending after updating some values for stereoscopic correction. Again, it remains "pending", the analysis is NOT interrupted and does not give errors!
The last messages are:
[I] CloudMasking: StereoCorrection Compute label statistics after changing value...
[I] CloudMasking: StereoCorrection Compute label statistics after changing value done

...and after...nothing!
Do you have any idea?
Thanks

Riccardo

**Comment by olivierhagolle** [comment]
Hi Riccardo,

Sorry for the troubles, it is true MAJA is not easy.

you should try Start_Maja,  it much easier, as it prepares thinks for you before running MAJA with its different modes. And it would much easier for myself to help too, as it is the way I work.

The  line you show is one of the places where MAJA needs a lot of memory, at least 8 GB. Maybe MAJA is swapping ?

One again, using  start_maja will be much easier.
Best regards,
Olivier

**Comment by RiccardoOr** [comment]
Hi Olivier,

I don't think MAJA is swapping, it runs on a server with 64GB.
Ok I'll try with Start_Maja and I hope it will be better.

Thank you so much and I'll update you on developments.
Regards,

Riccardo

**Comment by olivierhagolle** [comment]
OK, I am closing the issue, feel free to open a new one if you have issues with start_maja.
