### ISSUE TITLE
Commercial license?

### ISSUE THREAD

**Issue by lankestert** [olivierhagolle/Start_maja#27]
Hi, 
I see that this GitHub page has a GPL3 license but I assume that applies just to the start_maja scripts and files.
The MAJA page at CNES (https://logiciels.cnes.fr/en/license/58/145) has a different license that precludes commercial use.  Is there a commercial license that allows use of MAJA to prepare products in the scope of a commercial service?

Cordialement
Tom

**Comment by olivierhagolle** [comment]
Hi Thomas,
Yes, the GPL V3 only applies to Start MAJA. 
yes, I can send you the licence to sign, that allows commercial use of MAJA, for free. Please sent me your email (mine is olivier.hagolle at cnes.fr)
Best regards,
Olivier
