### ISSUE TITLE
Error: Most recent processed date

### ISSUE THREAD

**Issue by BM974** [olivierhagolle/Start_maja#28]
Hello,

After months of using MAJA without problems I get this error message when I start processing:

[matthias@maja-seas-oi Start_maja]$ python ./start_maja.py -f folders_new.txt -c MAJA_1_0_S2AS2B_NATIF -t 38KPA -s Madagascar -d 20170101
/DATA_MAJA/CACAOS/1C/L1C_2017/Madagascar//S2_OPER_PRD_MSIL1C*_None_*.SAFE/GRANULE/*38KPA*

Most recent processed date : 
[matthias@maja-seas-oi Start_maja]$ 

[MAJA_erreur_2019.txt](https://github.com/olivierhagolle/Start_maja/files/2767487/MAJA_erreur_2019.txt)

Do you have any idea what could have cause this error?

Thanks
Matthias

**Comment by olivierhagolle** [comment]
Closed after no reply in 5 months. please reopen if necessary
