### ISSUE TITLE
prepare_mnt archive

### ISSUE THREAD

**Issue by resnow92** [olivierhagolle/Start_maja#32]
Hello, 

is it possible to put the directetories conaining all SRTM and SWBD archives as input ? 
 
for exemple, the directorie "/mnt/data/DONNEES_AUX/SRTM" of the parametrization variable named "INDIR_MNT" doesn't contains only 3 or 4 srtm grids (individual .zip files) corresponding to one S2 tile, but contains the 872 srtm_x_x.tif files.

I would like to implement in one python script all tools to run MAJA automatically for random S2 tiles. And I would like to avoid to manually change parameters and download SRTM and SWBD files corresponding to the processed tile.

(NB: As it done in Sen2agri)

Thanks for your clarifications and advices.

**Comment by olivierhagolle** [comment]
Hi, sorry for the late answer.
In my installation, I have downloaded all the SWBD and SRTM tiles,  and the DTMCreation.py tool manages to find all the needed ones.

And by the way, this is an obsolete start_maja repository, the most recent one is here :
https://github.com/CNES/Start-MAJA/blob/master/Readme.md
Olivier

**Comment by resnow92** [comment]
Thanks for your answer! I will not use anymore this repository.
