### ISSUE TITLE
No SRTM over 60 degrees latitude

### ISSUE THREAD

**Issue by lefebvre-antoine** [olivierhagolle/Start_maja#34]
Hi Olivier !

I hope everything is OK for you in these days.

I recently faced a new issue with MAJA. I tried to process tiles over a latitude of 60 degrees and I have an error message. That reminds me that SRTM does not exist in these parts of the world. 

Do you have any advices to go over that issue ? 
Should we work with Aster GDEM v2 ? In this case, have you some tricks to share ?

By the way, how does ESA provide its L2 products in these parts of the world ? It seems they use the coarse Globe DEM at 1 km.

Thank you very much!

**Comment by olivierhagolle** [comment]
Hi Antoine,
Is it in Europe ? For our snow cover project for EEA, we use the EU-DEM 
https://land.copernicus.eu/user-corner/publications/eu-dem-flyer/view

But the converter to MAJA format has been made by Magellium and I don't have it. I will ask them if it is just a plugin to our start-mmaja tool, and if we can access it.

I know ESA was going to issue a global one, made by Airbus, for Sentinel-2, but I don't think it is available yet at 30m resolution.

Best regards,
Olivier

**Comment by lefebvre-antoine** [comment]
Hi Olivier, 

This is not in Europe...
I just found out some interesting information here :  https://github.com/CNES/Start-MAJA/issues/53
We may work on it !

Thank you very much,
Best regards
