### ISSUE TITLE
Elaboration on the documentation

### ISSUE THREAD

**Issue by Greforb** [olivierhagolle/Start_maja#5]
I originally posted these questions in the [STEP forum](http://forum.step.esa.int/t/normalize-l2a-reflectances-across-tiles-make-seamless/9574/) but Olivier Hagolle suggested to ask it here instead:

The folders.txt file seems to be not used during the [setup of Docker](https://github.com/olivierhagolle/Start_maja#docker), is that correct? It runs without changing the contents of this file at least. Don't know if it runs correctly though. It seems like the command for running Maja after setting up docker (`sudo docker run -v ~/maja/S2_NOMINAL:/data maja /opt/maja/core/1.0/bin/maja -i /data/input_maja1.0 -o /data/output_maja1.0 -m L2NOMINAL -ucs /data/userconf --TileId 36JTT`
) does not run it using the start_maja.py and this may be why folders.txt doesn't matter here? Anyways the usage of folders.txt is not clear to me. Is it supposed to contain info on the locations of the repcode, repwork etc inside the docker or on my actual machine? In the above command it seems like repL1 is given directly in the command (/data/input_maja1.0) together with repL2 (/data/output_maja1.0) etc...

I've found the conf folder, containing numerous xml files three of which has to do with Sentinel2. Which one to edit? And can i safely run Maja without editing these settings? In sen2cor I would probably wish to set some of the parameters to AUTO to tell sen2cor til automatically get the best values (for ozone for example). Is there a possibility for running Maja using multiple cores like sen2cor? That I guess would speed the process a whole lot?

Regarding the DEM; can I use the srtm one or will I be better off using a fine resolution lidar based one and if so how to prepare that and get it into my Docker container? I guess I will have to add it to my docker container using ADD? Or maybe this is already done if I use the docker-file found here?

**Comment by olivierhagolle** [comment]
And here is what was replied on the STEP forum:

I am not a computer guru, and I do not know much about docker.

Yes the example provided with docker did not involve start_maja.py. The start_maja.py script simplifies a lot your task. It is when you are using start_maja.py that you need the folders.txt. I do not know which folders are visible from within docker, but it seems logical to use visible folderscified folders within folders.txt are visible

Regarding the DEM, the readme file in github explains how to obtain them. MAJA needs a DEM to process the data. FRE data corrects for the terrain effects. It is a "Flattened REflectance".

**Comment by Greforb** [comment]
Thanks a lot for this elaboration, I should've posted it along with the above.
