### ISSUE TITLE
Weird tile differences

### ISSUE THREAD

**Issue by Greforb** [olivierhagolle/Start_maja#8]
I ran approximately 38 scenes through MAJA, but seem to get some quite weird results in some cases. In this image you see 4 tiles from the same scene processed by MAJA. Can anybody give me a clue on what's going wrong? Why are the values so much off in two of them compared to the others? Is it because there is too much water in them or how can this happen?
![sent2ex2](https://user-images.githubusercontent.com/11329273/40541189-10595702-601b-11e8-962d-1716cb8861de.jpg)

**Comment by olivierhagolle** [comment]
Hi Greforb,
When you open the tiles, I guess your viewer makes an automatic stretching depending on the content of the image. As the two tiles on the west have quite a lot of No data values, their histogram is quite different from the others. you should use a constant stretching, for instance stretching each RGB channel between 0 and 0.25 in reflectance units (0 and 2500 in numerical counts).
Olivier

**Comment by Greforb** [comment]
Thanks a lot. How embarrassing if this the reason! But thanks again for very quick and helpful reply. Checking right now!

**Comment by Greforb** [comment]
Amazing, this solved it. Sorry for de-coupling my brain...
